
x-service-volumes: &service-volumes
  - .:/app/:rw,cached

x-database-variables: &database-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: ${POSTGRES_HOST}




services:
  web:
    image: resumechallenge:latest
    container_name: AWSresumechallenge
    command: python manage.py runserver 0.0.0.0:443
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - postgres
    ports:
      - "443:443"
  db_migration:
    image: resumechallenge:latest
    command: python manage.py migrate
    volumes: *service-volumes
    environment: *app-variables



volumes:
  db-data:
#  driver: local
