
x-service-volumes: &service-volumes
  - .:/app/:rw,cached

services:
  web:
    image: resumechallenge:latest
    container_name: AWSresumechallenge
    command: gunicorn --bind 0.0.0.0:8000 resumechall.wsgi:application
#    depends_on:
#      - postgres
    volumes: *service-volumes
    env_file:
      - .env
    ports:
      - "80:8000"

volumes:
  db-data:
#  driver: local
