apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: db-migration
  name: db-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-migration
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: db-migration
    spec:
      containers:
        - args:
            - python
            - manage.py
            - migrate
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: resumechallenge:latest
          name: db-migration
          volumeMounts:
            - mountPath: /app
              name: db-migration-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: db-migration-cm0
          name: db-migration-cm0
