name: Deploy to EKS

permissions:
  id-token: write
  contents: read
on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2


    - name: Install kubectl and eksctl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin
        curl -s --location "https://github.com/weaveworks/eksctl/releases/download/v0.95.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Update kubeconfig for EKS cluster
      run: |
        aws eks update-kubeconfig --name eks-resumechallenge --region us-west-2

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Verify Kubernetes Access
      run: kubectl get nodes
      
    - name: Deploy Helm Chart to EKS
      env:
        AWS_REGION: us-west-2
      run: |
        helm upgrade --install resumechallenge ./helm/resumechallenge \
          --namespace default \
          --set image.repository=$396913714027.dkr.ecr.us-west-2.amazonaws.com/resumechallenge \
          --set image.tag=latest \
          --set image.pullPolicy=Always
