name: Deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily backup at midnight UTC

permissions:
  id-token: write
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Backup to S3
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::396913714027:role/github_actions
  #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2


    - name: Sync files to S3
      run: |
          aws s3 sync . s3://gregoriethomas.com --delete --exclude "bin/*" --exclude ".venv/*" --exclude ".git/*"  --exclude "resumechallenge/resumechallenge/bin/*" --exclude "/resumechallenge/pyvenv.cfg"

    
