name: Deploy to S3

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily backup at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Check AWS Access ID
      run: echo $AWS_ACCESS_KEY_ID
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    - name: Check AWS Access Key
      run: echo $AWS_SECRET_ACCESS_KEY
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload Backup to S3
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2





    - name: Sync files to S3
      run: |
          aws s3 sync . s3://gregoriethomas.com --delete --exclude "bin/*" --exclude ".venv/*" --exclude ".git/*"  --exclude "resumechallenge/resumechallenge/bin/*" --exclude "/resumechallenge/pyvenv.cfg"

    
