name: Update Route53 DNS

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Deploy to EKS"]
    types:
      - completed

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update Route53
      run: |
        aws route53 change-resource-record-sets --hosted-zone-id Z06311191J1NEAT206LO1 --change-batch file://.github/config/route53.json
